FROM node:18.18.0-alpine as build
WORKDIR /usr/src/app
COPY package.json .
RUN npm install
COPY ./ ./
RUN npm run build
FROM nginx
EXPOSE 3000
COPY --from=build /usr/src/app/dist/ /usr/share/nginx/html